### ISSUE TITLE
Errors building dependencies on OSX 10.11

### ISSUE THREAD

**Issue by eunikolsky** [elelay/gpodder-osx-bundle#3]
Hi @elelay,

I'm trying to build gPodder 3.9.0 on OSX 10.11.2 (Xcode 7.3), but ran into issues building the  dependencies. `bootstrap.sh` worked fine, but `build.sh` prints this:

```bash
➜  gpodder-osx-bundle git:(dev) ✗ ./build.sh
jhbuild build: failed to parse quodlibet: [Errno 2] No such file or directory: 'quodlibet'
W: Circular dependencies detected: meta-bootstrap -> xz -> automake -> automake
W: Circular dependencies detected: meta-bootstrap -> xz -> libtool -> libtool
W: bash has a dependency on unknown "readline" module
*** Checking out automake *** [1/22]
curl --continue-at - -L ftp://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz -o /Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_checkoutroot/pkgs/automake-1.15.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2191k  100 2191k    0     0   300k      0  0:00:07  0:00:07 --:--:--  300k
gzip -dc "/Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_checkoutroot/pkgs/automake-1.15.tar.gz" | tar xf -
*** Configuring automake *** [1/22]
./configure --prefix /Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix
./configure: line 154: /Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix/bin/bash: No such file or directory
./configure: line 154: exec: /Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix/bin/bash: cannot execute: No such file or directory
*** Error during phase configure of automake: ########## Error running ./configure --prefix /Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix    *** [1/22]

  [1] Rerun phase configure
  [2] Ignore error and continue to build
  [3] Give up on module
  [4] Start shell
  [5] Reload configuration
  [6] Go to phase "wipe directory and start over"
  [7] Go to phase "clean"
  [8] Go to phase "distclean"
choice:
```

the first error line is from `jhbuild build autoconf --nodeps`, the rest is `jhbuild bootstrap`. Tried with and without homebrew in `$PATH` — the same result.

Any ideas how to fix this?

**Comment by eunikolsky** [comment]
* btw, `jhbuild sanitycheck` finds a lot of missing stuff:
```
libtool >= 1.5 not found
gettext >= 0.10.40 not found
aclocal can't see libtool macros
aclocal can't see gettext macros
aclocal can't see pkg macros
Please copy the lacking macros (libtool.m4, gettext.m4, pkg.m4) in one of the following paths: /Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix/share/aclocal, /usr/share/aclocal, /usr/local/Cellar/automake/1.15/share/aclocal
Could not find DocBook XML DTD V4.1.2 in XML catalog (usually part of package 'docbook-xsl')
Could not find DocBook XSL Stylesheets in XML catalog (usually part of package 'docbook-xsl')
cvs not found
```

* apparently, this error `jhbuild build: failed to parse quodlibet: [Errno 2] No such file or directory: 'quodlibet'` is because this moduleset is mentioned in https://github.com/elelay/gpodder-osx-bundle/blob/master/misc/jhbuildrc-custom#L9, but the directory is missing in `modulesets/`.

**Comment by elelay** [comment]
Indeed, you should replace quodlibet with gpodder in the jhbuildrc-custom.
Thanks for the catch!

**Comment by eunikolsky** [comment]
@elelay, yes, I had figured it out yesterday. Changed it to `gpodder`, the first error is gone, but the build error is the same.

* I tried building on OSX 10.10.5 and it worked fine (until configuring `cmake`).

* I was able to build `quodlibet` with its scripts (up to `python`); they have been updated since the commit here (https://github.com/quodlibet/quodlibet/commits/master/osx_bundle). maybe, these scripts are outdated for 10.11?

**Comment by eunikolsky** [comment]
hurray! i'm past that error, waiting for the next one…

Found some hints about this problem: https://git.gnome.org/browse/gtk-osx/tree/jhbuildrc-gtk-osx-custom-example#n53 and http://stackoverflow.com/a/34894361; what i did in the end is updated `gtk-osx` scripts and applied this change: https://github.com/quodlibet/quodlibet/blob/master/osx_bundle/misc/quodlibet-jhbuildrc-custom#L19

I'll create a PR after the build is successful.

* another annoying point — a few times during the build, a window opens that says 'To use the "java" command-line tool you need to install a JDK.'

**Comment by elelay** [comment]
Thanks @eunikolsky, I'll gladly accept your PR.

I've got java on my machine, so the warning doesn't show up. Maybe it's called in autotools configure steps ? It should not be a dependency, that's for sure.

Coincidentally I've been testing the `release_from_linux.sh` script this week-end. It had to be adapted but I think I've built a working 3.9.0 this way.

**Comment by eunikolsky** [comment]
i now have an error when installing `openssl`:
```
W: Ignoring uninstalled package: openssl
Traceback (most recent call last):
  File "/Users/u/proj/py/gpodder-osx-bundle/_home/.local/bin/jhbuild", line 32, in <module>
    jhbuild.main.main(sys.argv[1:])
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/main.py", line 155, in main
    rc = jhbuild.commands.run(command, config, args, help=lambda: print_help(parser))
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/commands/__init__.py", line 183, in run
    return cmd.execute(config, args, help)
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/commands/__init__.py", line 52, in execute
    return self.run(config, options, args, help)
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/commands/base.py", line 268, in run
    return build.build()
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/frontends/buildscript.py", line 163, in build
    error, altphases = module.run_phase(self, phase)
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/modtypes/__init__.py", line 420, in run_phase
    method(buildscript)
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/modtypes/autotools.py", line 314, in do_install
    self.process_install(buildscript, self.get_revision())
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/modtypes/__init__.py", line 316, in process_install
    new_contents = fileutils.accumulate_dirtree_contents(destdir_prefix)
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/utils/fileutils.py", line 45, in accumulate_dirtree_contents
    _accumulate_dirtree_contents_recurse(path, contents)
  File "/Users/u/proj/py/gpodder-osx-bundle/_jhbuild/jhbuild/utils/fileutils.py", line 27, in _accumulate_dirtree_contents_recurse
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix/_jhbuild/root-openssl/Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix'
```

it appends `prefix` at the end of filepath, for some reason.

> Maybe it's called in autotools configure steps ?

indeed. `configure` for `cmake`, `bison`, and a few other packages check for java; i just removed useless `/usr/bin/java*`

> `release_from_linux.sh` script

do you mean i can build `gpodder` OSX app on linux?? or only bundle it?

**Comment by elelay** [comment]
> do you mean i can build gpodder OSX app on linux?? or only bundle it?
Only bundle it : I released a zip with gPodder dependencies ; the script then completes the process by installing your version of gPodder in the .app and doing a little post-processing.
Hopefully I'll release 3.9.0 this way Today.

**Comment by eunikolsky** [comment]
turns out the previous error is mentioned in the `README`: https://github.com/elelay/gpodder-osx-bundle/blob/master/README#L39  I fixed it (`openssl` doesn't understand the `DESTDIR` parameter to `make install`: http://comments.gmane.org/gmane.comp.encryption.openssl.user/51742).

@elelay, I think this info about bundling on linux should be added to the `README`. btw, how do you know when to update the dependencies and which are compatible versions? e.g., it'd be very nice to update `openssl`

**Comment by elelay** [comment]
I usually update all deps on gPodder release.  This time I'd rather release with old deps than not at all. 

I'll update the readme with Linux instructions.

**Comment by eunikolsky** [comment]
i've built `bootstrap` and `python` successfully. it now blows up at configuring `itstool`:
```
checking for python module libxml2... ./configure: line 2422: 43733 Done                    echo "import $py_module"
     43734 Abort trap: 6           | python - >&/dev/null
not found
```
and indeed i cannot `import libxml2` from the built `python`. the error indicates that there is mismatch of library versions, which it's very strange — i don't know how that `python` could get messed up with the system one. and `quodlibet`'s stuff builds fine.

**Comment by eunikolsky** [comment]
next! before configuring `gtk+`:
```
*** Applying patch http://git.gnome.org/browse/gtk-osx/plain/patches/0006-Bug-658722-Drag-and-Drop-sometimes-stops-working.patch *** [20/49]
patch -p1 < "/Users/u/proj/py/gpodder-osx-bundle/_home/.cache/jhbuild/0006-Bug-658722-Drag-and-Drop-sometimes-stops-working.patch"
patching file gdk/quartz/gdkdnd-quartz.c
patching file gtk/gtkdnd-quartz.c
Hunk #1 succeeded at 281 (offset 11 lines).
Hunk #2 succeeded at 353 (offset 17 lines).
Hunk #3 FAILED at 1934.
1 out of 4 hunks FAILED -- saving rejects to file gtk/gtkdnd-quartz.c.rej
```

**Comment by eunikolsky** [comment]
finally, after waiting for hours for `webkit`, the whole thing built fine! here's my first pr: #4.

the last(?) issue is with `bundle.sh`, or actually with `misc/provenance.pl`:
```
I: grabbing packages versions...
Unable to read /Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix/_jhbuild/packagedb.xml: No such file or directory
```
the reason is `jhbuild` stopped generating `packagedb.xml`: https://git.gnome.org/browse/jhbuild/commit/?id=10789b5da7b6f3ca9366842f34cda20b44274b7b i don't know its format, but what i could do is to merge `_jhbuild/info/*` into a file called `packagedb.xml`. however, @elelay, i noticed that in your bundle, `gPodder.contents` doesn't contain all the dependencies from `_jhbuild/info/`. here's my diff:
```diff
--- gPodder.contents	2016-04-30 23:45:55.000000000 -0700
+++ info.contents	2016-04-30 23:45:55.000000000 -0700
@@ -1,0 +2 @@
+adwaita-icon-theme
@@ -2,0 +4,9 @@
+autoconf
+automake
+automake-1.10
+automake-1.11
+automake-1.12
+automake-1.13
+automake-1.14
+bash
+bison
@@ -3,0 +14 @@
+cmake
@@ -6,0 +18 @@
+flex
@@ -13,0 +26,6 @@
+glib-networking
+gmp
+gnome-common
+gnutls
+gobject-introspection
+gpodder
@@ -14,0 +33 @@
+gtk-doc
@@ -17,0 +37 @@
+gtk-osx-docbook
@@ -19,0 +40 @@
+icon-naming-utils
@@ -20,0 +42,2 @@
+intltool
+itstool
@@ -23,0 +47 @@
+libnettle
@@ -26,0 +51 @@
+libtasn1
@@ -27,0 +53 @@
+libtool
@@ -31,0 +58 @@
+openssl
@@ -32,0 +60,2 @@
+perl-xml-parser
+perl-xml-simple
@@ -33,0 +63 @@
+pkg-config
@@ -39,0 +70 @@
+setuptools
@@ -43,0 +75,2 @@
+yelp-tools
+yelp-xsl
```

@elelay, any ideas about the script?

**Comment by elelay** [comment]
@eunikolsky #4 looks great!
Thank you so much for your tenacity :-)

Now my only concern is "does it still build on 10.6 ?". I'll try later. Don't hold your breath until you see it merged, but I hope to do it by the end of May.

`provenance.pl` shall be rewritten to use info files, if package.db is gone. I'll look into it later.

Not all packages are listed in gPodder.contents: only files actually shipped in gPodder.app are listed, most of packages in your diff look like build deps (perl scripts, setuptools) or maybe unused libraries (libnettle?). Did you generate it with provenance.pl ?

**Comment by eunikolsky** [comment]
hi @elelay.

> does it still build on 10.6 ?

i have no idea. and no osx 10.6 installer to try.

* that diff was generated with:
```bash
vimdiff <( egrep -o '^\S+' /opt/homebrew-cask/Caskroom/gpodder/3.9.0_0/gPodder.contents ) <( ls -1 gpodder-osx-bundle/_home/jhbuild_prefix/_jhbuild/info | sort )
```
I actually hacked a workaround for `provenance.pl`; take a look in #4: https://github.com/elelay/gpodder-osx-bundle/pull/4/commits/54c67dab35bc7e96b0726439fcce9c4e15ddf950; now my `gPodder.contents` is similar to yours:
```diff
--- /opt/homebrew-cask/Caskroom/gpodder/3.9.0_0/gPodder.contents	2015-12-24 18:33:02.000000000 -0800
+++ _build/gPodder.contents	2016-05-02 21:58:16.000000000 -0700
@@ -1,2 +1,2 @@
-WebKit 1.10.2-a0b0309e7f2e8a1189d5c19e9653948f
+WebKit 1.10.2-d9c3c6cebd3ce0a9ac9704e33d465655
   /lib/libjavascriptcoregtk-1.0.0.dylib
@@ -48,3 +48,144 @@
   /lib/libgthread-2.0.0.dylib
-gtk+ 2.24.28-08261543e57bb690f08014f554b911a6
+gpodder 45885de670522a26b53884a1ef9087b8034b5ad3-dirty
+  /bin/gpo
+  /bin/gpodder
+  /bin/gpodder-migrate2tres
+  /lib/python2.7/site-packages/gpodder/__init__.py
[…]
+gtk+ 2.24.28-64ef0c99316fd914941383657a007aee
   /lib/gtk-2.0/2.10.0/printbackends/libprintbackend-cups.so
@@ -291,3 +432,3 @@
   /lib/python2.7/site-packages/gtk-2.0/pangocairo.so
-python 2.7.8-53a930747aff1186253ffe4623424a14
+python 2.7.8-4f12325a1704f809186f4eee63946873
   /include/python2.7/abstract.h
@@ -715,3 +856,2 @@
   /lib/python2.7/lib-dynload/_functools.so
-  /lib/python2.7/lib-dynload/_hashlib.so
   /lib/python2.7/lib-dynload/_heapq.so
@@ -727,2 +867,3 @@
   /lib/python2.7/lib-dynload/_lsprof.so
+  /lib/python2.7/lib-dynload/_md5.so
   /lib/python2.7/lib-dynload/_Menu.so
@@ -739,2 +880,5 @@
   /lib/python2.7/lib-dynload/_Scrap.so
+  /lib/python2.7/lib-dynload/_sha.so
+  /lib/python2.7/lib-dynload/_sha256.so
+  /lib/python2.7/lib-dynload/_sha512.so
   /lib/python2.7/lib-dynload/_Snd.so
@@ -742,3 +886,2 @@
   /lib/python2.7/lib-dynload/_sqlite3.so
-  /lib/python2.7/lib-dynload/_ssl.so
   /lib/python2.7/lib-dynload/_struct.so
@@ -763,2 +906,3 @@
   /lib/python2.7/lib-dynload/future_builtins.so
+  /lib/python2.7/lib-dynload/gdbm.so
   /lib/python2.7/lib-dynload/gestalt.so
@@ -1111,3 +1255,3 @@
   /lib/libreadline.6.dylib
-shared-mime-info 1.3-d41d8cd98f00b204e9800998ecf8427e
+shared-mime-info 0.90-d41d8cd98f00b204e9800998ecf8427e
   /share/mime/aliases
@@ -1117,11 +1261,8 @@
   /share/mime/application/dicom.xml
+  /share/mime/application/docbook+xml.xml
   /share/mime/application/ecmascript.xml
   /share/mime/application/epub+zip.xml
-  /share/mime/application/font-woff.xml
-  /share/mime/application/gml+xml.xml
   /share/mime/application/gnunet-directory.xml
-  /share/mime/application/gzip.xml
   /share/mime/application/illustrator.xml
   /share/mime/application/javascript.xml
-  /share/mime/application/json.xml
   /share/mime/application/mac-binhex40.xml
[…]
```

* `bundle.sh` prints these warnings at startup, but seems to work fine:
```
('Warning, library not available in any prefix:', '/usr/local/opt/gdbm/lib/libgdbm.4.dylib')
('Warning, library not available in any prefix:', '/Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_checkoutroot/py2cairo-1.10.0/build_directory/src/_cairo.so')
('Warning, library not available in any prefix:', '/Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_checkoutroot/py2cairo-1.10.0/build_directory/src/_cairo.so')
('Warning, library not available in any prefix:', '/usr/local/opt/gdbm/lib/libgdbm.4.dylib')
('Warning, library not available in any prefix:', '/Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_checkoutroot/py2cairo-1.10.0/build_directory/src/_cairo.so')
('Warning, library not available in any prefix:', '/usr/local/opt/gdbm/lib/libgdbm.4.dylib')
('Warning, library not available in any prefix:', '/Users/u/proj/py/gpodder-osx-bundle/_home/jhbuild_checkoutroot/py2cairo-1.10.0/build_directory/src/_cairo.so')
('Warning, library not available in any prefix:', '/usr/local/opt/gdbm/lib/libgdbm.4.dylib')
```

* and the last thing, i had this error when launching bundled gPodder:
```
1462162820.278846 [gpodder.sync] WARNING: Could not find eyed3.mp3
/Users/u/proj/py/gpodder-osx-bundle/_build/gPodder.app/Contents/Resources/lib/python2.7/site-packages/gpodder/gtkui/draw.py:300: GtkWarning: Cannot open pixbuf loader module file '_build/gPodder.app/Contents/Resources/etc/gtk-2.0/gdk-pixbuf.loaders': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > _build/gPodder.app/Contents/Resources/etc/gtk-2.0/gdk-pixbuf.loaders
to make things work again for the time being.
  pbl.close()
1462162820.367392 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "_build/gPodder.app/Contents/Resources/bin/gpodder", line 156, in <module>
    main()
  File "_build/gPodder.app/Contents/Resources/bin/gpodder", line 151, in main
    main.main(options)
  File "/Users/u/proj/py/gpodder-osx-bundle/_build/gPodder.app/Contents/Resources/lib/python2.7/site-packages/gpodder/gtkui/main.py", line 3478, in main
    float(EpisodeListModel.PROGRESS_STEPS))
  File "/Users/u/proj/py/gpodder-osx-bundle/_build/gPodder.app/Contents/Resources/lib/python2.7/site-packages/gpodder/gtkui/draw.py", line 276, in draw_cake_pixbuf
    return cairo_surface_to_pixbuf(draw_cake(percentage, text, emblem))
  File "/Users/u/proj/py/gpodder-osx-bundle/_build/gPodder.app/Contents/Resources/lib/python2.7/site-packages/gpodder/gtkui/draw.py", line 300, in cairo_surface_to_pixbuf
    pbl.close()
GError: Unrecognized image file format
```
so I did add the suggested command: https://github.com/elelay/gpodder-osx-bundle/pull/4/commits/941efe1f6b9c0371e3223cf29e257a0021cf39b4

**Comment by eunikolsky** [comment]
and here is a few enhancements i came up with during this process: #5.

**Comment by elelay** [comment]
@eunikolsky great work !
As soon as I have time and access to the mac I'll merge and test.
Hopefully this week.
